version: '3'
networks:
  selenoid:
    name: selenoid
    external: true
services:
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:latest"
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/etc/selenoid"
      - "./logs:/opt/selenoid/logs"
      - "./target:/opt/selenoid/video"
      - "./target:/output"
    environment:
      - "OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/target"
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8083:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome_120.0:
    image: "selenoid/vnc:chrome_120.0"
    container_name: chrome_120.0
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - selenoid
    volumes:
      - "/dev/shm:/dev/shm"
  test_framework:
    build: .
    image: test_framework_img
    depends_on:
      - selenoid
      - selenoid-ui
      - chrome_120.0
    networks:
      - selenoid
    volumes:
      - ./:/usr/src/test_framework
      - /dev/shm:/dev/shm